version: '3'
services:
    mysql:
        image: mysql:8.0.32
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: admin
        # command:
        #   - --character-set-server=utf8mb4
        #   - --collation-server=utf8mb4_unicode_ci
        #   - --innodb-buffer-pool-size=2G
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./query/:/docker-entrypoint-initdb.d
    redis:
        image: redis:latest
        container_name: redis
        hostname: redis_boot
        labels:
            - "name=redis"
            - "mode=standalone"
        ports:
            - 6379:6379
        command: redis-server --port 6379
